# -*- coding: utf-8 -*-
"""Car Parking lot LLD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UPmafhqKMTx4B8hQFok1o5tkpw2PguCN
"""

slots = []
available_pos = [i for i in range(1,100)]
# position = 1
# available_pos

class slot():
  def __init__(self,num,col,posi):
    self.pos = posi
    self.number = num
    self.color = col




class car():
    def __init__(self,number,color):
        registration_no = number
        color = color




class parking_arena():
    def __init__(self,n):
        # lst = ['null=']*n
        max_n = n
        size = 0


    # complete
    def add_car(self):

        # edge
        if position == 100:
            print("Max limit reached!!")
            return

        # take input
        print("Enter registration number :- ",end=" ")
        number = int(input())
        print("Enter color :-",end=" ")
        color = input()


        #  park in closest availablle slot
        pos = available_pos[0]
        new_car = slot(number,color, pos)
        slots.append(slot(number, color, pos))
        print("Car parked in slot number:- " + str(pos))

        # mark that slot as unavailable
        available_pos.remove(pos)
        # print(available_pos)
        # print(len(slots))


    # complete
    def remove_car(self):

        # take input
        print("Enter registration number :- ",end=" ")
        number = int(input())


        # remove that car from slots array
        rem = 0

        for i, o in enumerate(slots):
          if o.number == number:
              rem = o.pos
              del slots[i]
              break
        # for s in slots:
        #   if s.number == number and s.color == color:
        #     slots.remove(slot(number,color,s.pos))
        #     rem = s.pos
        
        print("Car removed from slot number:- " + str(rem))

        # mark that slot as available
        available_pos.append(rem);
        available_pos.sort()
        pass

    def cars_with_particular_color(self):
        print("Enter color :-")
        target_color = input()
        ans = []
        for i in slots:
          if i.color == target_color:
            ans.append((i.number , i.pos))
        
        for i in ans:
          print(i)      #(registration number , slot number)
        
        pass

    def slot_of_given_car(self):
        # take input
        print("Enter registration number :- ",end=" ")
        number = int(input())

        for s in slots:
          if s.number == number:
            print("Slot Given :- " + str(s.pos))
        pass

    def slots_of_given_color(self):
        # take input
        print("Enter color :-",end=" ")
        color = input()

        for s in slots:
          if s.color == color:
            print("Slot with given color :- " + str(s.pos))
        pass

if __name__ == '__main__':
    # print('Enter size of parking arena :-', end=" ")
    # n = int(input())
    n = 10
    arena = parking_arena(n)


    while True:
        print('---------------------------------------------------')
        print('press 1 to add car in parking area.')
        print('press 2 to remove a car from parking area.')
        print('press 3 to find registration numbers of all cars of a particular color.')
        print('press 4 to find slot number in which a car with a given registration number is parked.')
        print('press 5 to final slot numbers of all slots where a car of a particular color is parked.')
        print('press 6 to exit program')
        print()
        print()
        print("Enter choice :-",end=" ")
        choice = int(input())

        if choice == 1:
            arena.add_car()

        elif choice == 2:
            arena.remove_car()

        elif choice == 3:
            arena.cars_with_particular_color()

        elif choice == 4:
            arena.slot_of_given_car()

        elif choice == 5:
            arena.slots_of_given_color()

        elif choice == 6:
            print('-------------code executed sucessfully--------------')
            break
            
        print('---------------------------------------------------')